force-app/main/default/objects/AWSSettings__mdt/AWSSettings__mdt.object-meta.xml
<CustomObject>
    <label>AWSSettings</label>
    <pluralLabel>AWSSettings</pluralLabel>
</CustomObject>

force-app/main/default/objects/AWSSettings__mdt/fields/Electronic_Signature__c.field-meta.xml
<CustomField>
    <fullName>Electronic_Signature__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Electronic Signature</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AWSSettings__mdt/fields/Push_to_AWS__c.field-meta.xml
<CustomField>
    <fullName>Push_to_AWS__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Push to AWS</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AWSSettings__mdt/fields/Signature_Status__c.field-meta.xml
<CustomField>
    <fullName>Signature_Status__c</fullName>
    <label>Signature Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Signed</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Revoked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RSI_checkMetadata1.cls
public class RSI_checkMetadata1 {
    @future(callout=false)
    //public static void performMetaActions(Map<Id,SBQQ__QuoteDocument__c> quoteDocumentIdMapTest) {
    public static void performMetaActions(Set<Id> quoteDocumentId) {    
        Map<Id,SBQQ__QuoteDocument__c> quoteDocumentIdMapTest = new Map<Id,SBQQ__QuoteDocument__c>([SELECT Id, SBQQ__ElectronicSignature__c, SBQQ__SignatureStatus__c FROM SBQQ__QuoteDocument__c Where Id IN: quoteDocumentId]);
        RSI_QuoteToAWS pushQuoteToAws;
        AWSSettings__mdt awsSettings = [SELECT Push_to_AWS__c, Electronic_Signature__c, Signature_Status__c FROM AWSSettings__mdt];
    	if(awsSettings.Push_to_AWS__c == true) {
            if(awsSettings.Electronic_Signature__c == true || awsSettings.Signature_Status__c!='') {
                for(SBQQ__QuoteDocument__c qd : quoteDocumentIdMapTest.values()) {
                    if(qd.SBQQ__ElectronicSignature__c==true || (awsSettings.Signature_Status__c==qd.SBQQ__SignatureStatus__c) ) {
                        System.enqueueJob(new RSI_QuoteToAWS(quoteDocumentIdMapTest));
                    }
                }
            }
            else {
                System.enqueueJob(new RSI_QuoteToAWS(quoteDocumentIdMapTest));
            }
        }
    }
}